"""Add listing conversation state

Revision ID: 93deccb20018
Revises: caa10990c258
Create Date: 2026-08-25 15:31:53.332861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93deccb20018'
down_revision: Union[str, Sequence[str], None] = 'caa10990c258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('pending_listing', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'pending_listing')
    # ### end Alembic commands ###
